This is makeindex, version 2.15 [MiKTeX 2.9 64-bit] (kpathsea + Thai support).
Scanning style file ./rpithes.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file rpithes.acn....done (242 entries accepted, 0 rejected).
Sorting entries.....done (2261 comparisons).
Generating output file rpithes.acr....done (172 lines written, 0 warnings).
Output written in rpithes.acr.
Transcript written in rpithes.alg.
